// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu9EtuLPEr0Ap1JM6WZwQZlGMooak83hc',
    appId: '1:1079187906983:web:23ba20774259e8f5205682',
    messagingSenderId: '1079187906983',
    projectId: 'havenfinder-76fac',
    authDomain: 'havenfinder-76fac.firebaseapp.com',
    storageBucket: 'havenfinder-76fac.appspot.com',
    measurementId: 'G-R4XT987V1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgZgWljjNxiR3YPtsOMeQ1E-TiYCMTJkU',
    appId: '1:1079187906983:android:811a8e299ec2d873205682',
    messagingSenderId: '1079187906983',
    projectId: 'havenfinder-76fac',
    storageBucket: 'havenfinder-76fac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpRgK__-pBDsEM9ZlpW3_z9BfcqNmE3aA',
    appId: '1:1079187906983:ios:349273df02f168b8205682',
    messagingSenderId: '1079187906983',
    projectId: 'havenfinder-76fac',
    storageBucket: 'havenfinder-76fac.appspot.com',
    iosClientId: '1079187906983-g0s3382c812m65snlnjujo6n0rntctid.apps.googleusercontent.com',
    iosBundleId: 'com.example.havenfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpRgK__-pBDsEM9ZlpW3_z9BfcqNmE3aA',
    appId: '1:1079187906983:ios:349273df02f168b8205682',
    messagingSenderId: '1079187906983',
    projectId: 'havenfinder-76fac',
    storageBucket: 'havenfinder-76fac.appspot.com',
    iosClientId: '1079187906983-g0s3382c812m65snlnjujo6n0rntctid.apps.googleusercontent.com',
    iosBundleId: 'com.example.havenfinder',
  );
}
